### ISSUE TITLE
can make a pkg repaker?

### ISSUE THREAD

**Issue by BigFai** [sup817ch/tr_pkgtool#1]
Thanks for your share. I can unpack the pkg file now, but I can't repack it to pkg file.

**Comment by sup817ch** [comment]
repack is more difficult than unpack, and repack is not necessary for me.
I made this unpacker just for fun, sorry.

**Comment by LuoHui666** [comment]
大哥 你是真的牛皮,港服最新的都能解密,只是限制了100k? 
大哥我是開私服的 能不能幫我弄個封包帶文件加密的 1906的trgame
我有封包源碼,如果你懂的求你幫我弄個加密功能,萬分感謝
qq376521838

**Comment by sup817ch** [comment]
> 大哥 你是真的牛皮,港服最新的都能解密,只是限制了100k?
> 大哥我是開私服的 能不能幫我弄個封包帶文件加密的 1906的trgame
> 我有封包源碼,如果你懂的求你幫我弄個加密功能,萬分感謝
> qq376521838

已修复只解密100k的BUG
