### ISSUE TITLE
AES Key

### ISSUE THREAD

**Issue by Oesis** [sup817ch/tr_pkgtool#2]
I have question what method can find AES Key ?

**Comment by sup817ch** [comment]
The only answer I can tell you is reverse engineering.

**Comment by TheNineZ** [comment]
Oh thank now i got AES Key can your make Repack Pkg ?

**Comment by Oesis** [comment]
Now i found AES Key and try decrypt it work thank you for sharing !

**Comment by LuoHui666** [comment]
> Now i found AES Key and try decrypt it work thank you for sharing !

wow!repack to private server?
